spring:
  redis:
    host: localhost
    port: 6379
    username:
    password:
    client-type: JEDIS
    jedis:
      pool:
        enabled: true
        max-active: 7
        max-idle: 7
        min-idle: 2
        max-wait: -1ms

  cache:
    type: REDIS
    redis:
      time-to-live: 120  # seconds
      cache-null-values: false

