spring:
  redis:
    host: localhost
    port: 6379


  cache:
    type: REDIS
    redis:
      enable-statistics: true
      time-to-live: 60
      use-key-prefix: true
      cache-null-values: true

